const data = [
    {
        id: 1,
        title: "buttermilk pancakes",
        category: "breakfast",
        price: 15.99,
        img: "https://res.cloudinary.com/dnnpulqtc/image/upload/v1655181161/menu/item-1_tnvd26.jpg",
        desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
        id: 2,
        title: "diner double",
        category: "lunch",
        price: 13.99,
        img: "https://res.cloudinary.com/dnnpulqtc/image/upload/v1655182701/menu/ee8cdb19ec70ec5f6780c296166287eb_bgxrer.jpg",
        desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
        id: 3,
        title: "godzilla milkshake",
        category: "shakes",
        price: 6.99,
        img: "https://res.cloudinary.com/dnnpulqtc/image/upload/v1655182879/menu/0_DSC_5334-copy-1_ohoi4p.jpg",
        desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
        id: 4,
        title: "country delight",
        category: "breakfast",
        price: 20.99,
        img: "https://res.cloudinary.com/dnnpulqtc/image/upload/v1655182961/menu/DANevY6XgAAzEKB_ltcqyd.jpg",
        desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
        id: 5,
        title: "egg attack",
        category: "lunch",
        price: 22.99,
        img: "https://res.cloudinary.com/dnnpulqtc/image/upload/v1655183094/menu/4517729_cxd3jj.jpg",
        desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
        id: 6,
        title: "oreo dream",
        category: "shakes",
        price: 18.99,
        img: "https://res.cloudinary.com/dnnpulqtc/image/upload/v1655183117/menu/cheesecake-factory-oreo-dream-extreme-cheesecake-copycat-recipe_ilwxgn.jpg",
        desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
        id: 7,
        title: "bacon overflow",
        category: "breakfast",
        price: 8.99,
        img: "https://res.cloudinary.com/dnnpulqtc/image/upload/v1655183143/menu/BACON-WRAPPED-QUESO-STUFFED-JALAPENOS-By-Chef-Aaro_CC_81n-Sa_CC_81nchez-web_hwruzm.jpg",
        desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
        id: 8,
        title: "american classic",
        category: "lunch",
        price: 12.99,
        img: "https://res.cloudinary.com/dnnpulqtc/image/upload/v1655183399/menu/39078181-lunch-menu-with-classic-american-cheese-burger-french-fries-and-vegetable-salad_bgm600.jpg",
        desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
        id: 9,
        title: "quarantine buddy",
        category: "shakes",
        price: 16.99,
        img: "https://res.cloudinary.com/dnnpulqtc/image/upload/v1655183467/menu/EVhDJHHWoAAEbkB_mzgzcg.jpg",
        desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
];
export default data;
